import { NextResponse } from 'next/server';

// Expositions du Musée d'Orsay avec périodes réelles
const ORSAY_EXHIBITIONS = [
  {
    id: 'orsay-sargent',
    title: 'John Singer Sargent - Éblouir Paris',
    slug: 'john-singer-sargent-eblouir-paris',
    description: 'Première grande rétrospective en France consacrée à John Singer Sargent (1856-1925), figure majeure de la peinture de la fin du XIXe siècle. L\'exposition explore son rapport à Paris et à la scène artistique française, depuis ses années de formation jusqu\'à sa consécration internationale.',
    shortDescription: 'Rétrospective exceptionnelle du maître américain, virtuose du portrait et de la lumière.',
    dateStart: '2024-10-15',
    dateEnd: '2026-01-11',
    status: 'current',
    price: 16,
    priceReduced: 13,
    image: 'https://www.musee-orsay.fr/sites/default/files/2024-09/sargent-affiche.jpg',
    bookingUrl: 'https://billetterie.musee-orsay.fr/',
    featured: true,
    tags: ['peinture', 'portrait', 'impressionnisme', 'américain'],
  },
  {
    id: 'orsay-troubetzkoy',
    title: 'Paul Troubetzkoy - Sculpteur (1866-1938)',
    slug: 'paul-troubetzkoy-sculpteur',
    description: 'Première exposition monographique en France dédiée au sculpteur italo-russe Paul Troubetzkoy. Ses œuvres impressionnistes saisissent l\'instant avec une virtuosité remarquable, immortalisant les figures de son époque avec une spontanéité et une élégance uniques.',
    shortDescription: 'Découvrez le sculpteur impressionniste qui a immortalisé l\'élégance de la Belle Époque.',
    dateStart: '2024-10-15',
    dateEnd: '2026-01-11',
    status: 'current',
    price: 16,
    priceReduced: 13,
    image: null,
    bookingUrl: 'https://billetterie.musee-orsay.fr/',
    featured: false,
    tags: ['sculpture', 'impressionnisme', 'portrait', 'belle époque'],
  },
  {
    id: 'orsay-riley',
    title: 'Bridget Riley - Point de départ',
    slug: 'bridget-riley-point-de-depart',
    description: 'Exposition contemporaine dédiée à Bridget Riley, figure majeure de l\'art optique. L\'artiste britannique dialogue avec les collections impressionnistes du musée d\'Orsay dans une exploration fascinante de la perception visuelle et de la couleur.',
    shortDescription: 'L\'art optique rencontre l\'impressionnisme dans un dialogue visuel saisissant.',
    dateStart: '2024-10-22',
    dateEnd: '2026-01-25',
    status: 'current',
    price: 16,
    priceReduced: 13,
    image: null,
    bookingUrl: 'https://billetterie.musee-orsay.fr/',
    featured: true,
    tags: ['art contemporain', 'art optique', 'abstraction', 'couleur'],
  },
  {
    id: 'orsay-hebert',
    title: 'Gabrielle Hébert - Amour fou à la Villa Médicis',
    slug: 'gabrielle-hebert-amour-fou',
    description: 'Exposition consacrée à Gabrielle Hébert, explorant sa relation passionnée avec le sculpteur Ernest Hébert lors de leurs années à la Villa Médicis à Rome. Un voyage au cœur de l\'art et de l\'amour au XIXe siècle, à travers des œuvres et correspondances inédites.',
    shortDescription: 'Une histoire d\'amour passionnée entre artistes à la Villa Médicis.',
    dateStart: '2024-11-05',
    dateEnd: '2026-02-15',
    status: 'current',
    price: 16,
    priceReduced: 13,
    image: null,
    bookingUrl: 'https://billetterie.musee-orsay.fr/',
    featured: false,
    tags: ['art romantique', 'histoire', 'villa médicis', 'XIXe siècle'],
  },
  {
    id: 'orsay-renoir-dessinateur',
    title: 'Renoir dessinateur',
    slug: 'renoir-dessinateur',
    description: 'Exposition dédiée à l\'œuvre graphique d\'Auguste Renoir, révélant un aspect méconnu de son art. Dessins, pastels et études préparatoires témoignent de la maîtrise technique et de la sensibilité du maître impressionniste.',
    shortDescription: 'Découvrez le Renoir intime à travers ses dessins et études.',
    dateStart: '2026-03-17',
    dateEnd: '2026-07-05',
    status: 'upcoming',
    price: 16,
    priceReduced: 13,
    image: null,
    bookingUrl: 'https://billetterie.musee-orsay.fr/',
    featured: true,
    tags: ['dessin', 'renoir', 'impressionnisme', 'études'],
  },
  {
    id: 'orsay-renoir-amour',
    title: 'Renoir et l\'amour',
    slug: 'renoir-et-lamour',
    description: 'Grande exposition thématique explorant le thème de l\'amour dans l\'œuvre de Pierre-Auguste Renoir. Des premiers portraits intimes aux grandes compositions, une célébration de la tendresse, de la sensualité et de la joie de vivre qui caractérisent l\'art du maître.',
    shortDescription: 'L\'amour sous toutes ses formes dans l\'œuvre de Renoir.',
    dateStart: '2026-03-17',
    dateEnd: '2026-07-19',
    status: 'upcoming',
    price: 16,
    priceReduced: 13,
    image: null,
    bookingUrl: 'https://billetterie.musee-orsay.fr/',
    featured: true,
    tags: ['renoir', 'amour', 'impressionnisme', 'portrait'],
  },
];

const MUSEUM_INFO = {
  name: 'Musée d\'Orsay',
  address: '1 Rue de la Légion d\'Honneur, 75007 Paris',
  arrondissement: 7,
  website: 'https://www.musee-orsay.fr',
  bookingUrl: 'https://billetterie.musee-orsay.fr/',
  phone: '+33 1 40 49 48 14',
  metro: ['Solférino (ligne 12)', 'Musée d\'Orsay (RER C)'],
  hours: {
    regular: '9h30 - 18h00',
    thursday: '9h30 - 21h45 (nocturne)',
    closed: 'Fermé le lundi',
  },
  prices: {
    full: 16,
    reduced: 13,
    free: 'Gratuit pour les moins de 18 ans, les 18-25 ans résidents UE',
    firstSunday: 'Gratuit le 1er dimanche du mois',
  },
  description: 'Le musée d\'Orsay est un musée national situé à Paris, sur la rive gauche de la Seine. Il présente la plus importante collection d\'art impressionniste et post-impressionniste au monde, avec des chefs-d\'œuvre de Monet, Renoir, Van Gogh, Cézanne, Degas et bien d\'autres.',
  image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Mus%C3%A9e_d%27Orsay%2C_Paris_7e%2C_France.jpg/1200px-Mus%C3%A9e_d%27Orsay%2C_Paris_7e%2C_France.jpg',
};

export async function GET() {
  return NextResponse.json({
    success: true,
    museum: MUSEUM_INFO,
    exhibitions: ORSAY_EXHIBITIONS,
    currentCount: ORSAY_EXHIBITIONS.filter(e => e.status === 'current').length,
    upcomingCount: ORSAY_EXHIBITIONS.filter(e => e.status === 'upcoming').length,
  });
}


